controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    robot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    robot_effort_controller:
      type: robot_controllers/MyController


robot_effort_controller:
  ros__parameters:
    joints:
      - left1_wheel_joint
      - left2_wheel_joint
      - right1_wheel_joint
      - right2_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort


