pid_effort_controller:
  ros__parameters:
    joints:
      - left_front_wheel_joint
      - right_front_wheel_joint
      - left_rear_wheel_joint
      - right_rear_wheel_joint
    kp: 5.0
    ki: 0.0
    kd: 0.1
